### ISSUE TITLE
InputDevices

### ISSUE THREAD

**Issue by Metarock13** [fariazz/zenvavr#1]
Hello!

Assets\ZenvaVR\Toolkit\Scripts\AutoPoseSource.cs(37,26): error CS0117: 'InputDevices' does not contain a definition for 'GetDevicesWithCharacteristics'

Assets\ZenvaVR\Toolkit\Scripts\AutoPoseSource.cs(37,56): error CS0103: The name 'InputDeviceCharacteristics' does not exist in the current context

Unity 2019.1.14f1

What to do to work?

**Comment by octatone** [comment]
I see the same error for 2019.2.12f1.  Why was this issue closed?
