### ISSUE TITLE
Issue with AutoPoseSource.cs

### ISSUE THREAD

**Issue by octatone** [fariazz/zenvavr#2]
In Unity 2019.2.12f1 I see the following error in the console when adding this library as an asset:

```
Assets\ZenvaVR\Toolkit\Scripts\AutoPoseSource.cs(36,26): error CS0117: 'InputDevices' does not contain a definition for 'GetDevicesWithCharacteristics'
```

**Comment by DBuckley101** [comment]
Hey @octatone 'GetDevicesWithCharacteristics' is a recent change along with a few others to the UnityEngine.XR library in 2019.3. So switching over to 2019.3 (becoming the official build very soon) will fix this issue.
